name: hirise-api

on: [push]

jobs:
  project-plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest -vv ../HIRISE_api/tests/test_download_data.py::TestHIRISEdownload
          pytest -vv .HIRISE_api/tests/test_getinfo.py:: TestHIRISEinfo